#!/bin/bash
# TODO: will be repeated, but everything except for LPCs should be ok

# Daisy scan numbers:
# 16:18,23:34 | mapped those with a wrong value of vlsr in source.cat (30 instead of 65.8 km/s)
# 70:81,84:86 | daisy scans at the end of the run, with corrected vlsr value

# clear the AIPS catalogue to solve the annoying bug causeing the pipeline to crash:
aipspy /home/gbtpipeline/release/tools/clear_AIPS_catalog.py `id -u`

# run the pipeline
gbtpipeline --clobber -u tmb --window 2 -m "70:81,84:86" -f 0,1,3,4,5,6 -i /home/scratch/vsokolov/AGBT15B_313_03.raw.vegas
