#!/bin/bash
# TODO: figure out how to include window 3 and fdnum=2
# TODO: image other windows
# TODO: get the scaling factors: --beam-scaling BEAMSCALING
# TODO: try to megre with AGBT15B_313_01.raw.vegas, -m 41:45

# Daisy scan numbers:
# 20:31,45:48

# clear the AIPS catalogue to solve the annoying bug causeing the pipeline to crash:
aipspy /home/gbtpipeline/release/tools/clear_AIPS_catalog.py `id -u`

# run the pipeline
gbtpipeline --clobber -u tmb --window 2 -m "20:31,45:48" -f 0,1,3,4,5,6 -i /home/scratch/vsokolov/AGBT15B_313_02.raw.vegas
