#!/bin/bash
# TODO: figure out how to include window 3 and fdnum=2
# TODO: image other windows
# TODO: get the scaling factors: --beam-scaling BEAMSCALING
# TODO: check the pointing offsets together with Dan

# Daisy scan numbers:
# 20:31 | from 313-01; done with a wrong value of vlsr in source.cat (16.2 instead of 22 km/s), and with wrong daisy period, AND with a wrong pointing calibrator! wow if you ever feel that life's too easy, feel free to try to recover those; Первый блин - комом.
# 105:113 | from 313-04; did pointing corrections on 1751+0939, and nodding on 3C84 (scans 114:121); a total daisy map of 9x4=36 minutes, a bit less than the other clouds but the lines look strong;
# 2015/12/09 vsokolov: scan 113 is empty and crashes the pipeline - that must be when I hit abort in Astrid

# clear the AIPS catalogue to solve the annoying bug causeing the pipeline to crash:
aipspy /home/gbtpipeline/release/tools/clear_AIPS_catalog.py `id -u`

# run the pipeline
#gbtpipeline --clobber -u tmb --window 2 -m "20:31" -f 0,1,3,4,5,6 -i /home/scratch/vsokolov/AGBT15B_313_01.raw.vegas
gbtpipeline --clobber -u tmb --window 2 -m "105:112" -f 0,1,3,4,5,6 -i /home/scratch/vsokolov/AGBT15B_313_04.raw.vegas
