#!/bin/bash
# TODO: will repeat, bad pointings

# Daisy scan numbers:
# 49:60 | mapped those with a wrong value of vlsr in source.cat (28.5 instead of ?? km/s)

# clear the AIPS catalogue to solve the annoying bug causeing the pipeline to crash:
aipspy /home/gbtpipeline/release/tools/clear_AIPS_catalog.py `id -u`

# run the pipeline
gbtpipeline --clobber -u tmb --window 2 -m "49:60" -f 0,1,3,4,5,6 -i /home/scratch/vsokolov/AGBT15B_313_03.raw.vegas
